# Generated by Django 6.0.3 on 2026-03-07 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
    ]
