# Generated by Django 6.0.3 on 2026-03-07 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_category_is_active"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table=None,
        ),
    ]
